<<<<<<< HEAD
name: âŠ• New Issue Processing

on:
  issues:
    types: [opened, edited, labeled]
=======
name: New Issue Processing

on:
  issues:
    types: [opened, edited]
>>>>>>> fabd696 (Initial commit)

permissions:
  issues: write
  contents: write
  id-token: write
  pull-requests: write

<<<<<<< HEAD
jobs:
  new-issue:
    runs-on: ubuntu-latest
    # Only run if the issue has the 'Review' label
    if: contains(github.event.issue.labels.*.name, 'Review')
=======
# concurrency:
#   group: "pages"
#   cancel-in-progress: true

jobs:
  # Specify the machine type
  new-issue:
    runs-on: ubuntu-latest  # Added missing runs-on field
>>>>>>> fabd696 (Initial commit)

    steps:
      - name: Run the parser on a new issue
        id: new-issue-action
        uses: WCRP-CMIP/CMIPLD/actions/new-issue@main
